{% set major = "1.42" %}
{% set patch = "1" %}
{% set version = major + "." + patch %}

package:
  name: pango
  version: {{ version }}

source:
  url: http://ftp.gnome.org/pub/GNOME/sources/pango/{{ major }}/pango-{{ version }}.tar.xz
  sha256: 915a6756b298578ff27c7a6393f8c2e62e6e382f9411f2504d7af1a13c7bce32

build:
  number: 2
  skip: true  # [win]
  run_exports:
    # excellent: https://abi-laboratory.pro/tracker/timeline/pango/
    - {{ pin_subpackage('pango') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ cdt('libxau-devel') }}           # [linux]
    - {{ cdt('libxext-devel') }}          # [linux]
    - {{ cdt('libx11-devel') }}           # [linux]
    - {{ cdt('libxrender-devel') }}       # [linux]
    - make                                # [unix]
  host:
    - cairo
    - fontconfig
    - freetype
    - fribidi
    - glib
    - gobject-introspection               # [not win]
    - graphite2                           # [linux]
    - harfbuzz
    - icu                                 # [linux]
    - libffi                              # [linux]
    - libpng
    - libuuid                             # [linux]
    - libxml2                             # [linux]
    - pcre                                # [linux]
    - perl 5.*
    - pixman                              # [linux]
    - pkg-config
    - xz                                  # [linux]
    - zlib                                # [linux]

test:
  commands:
    - pango-view --help

about:
  home: http://www.pango.org/
  license: LGPL-2.1
  license_file: COPYING
  summary: 'Text layout and rendering engine.'
  description: |
    Pango is a library for laying out and rendering of text, with an emphasis
    on internationalization. Pango can be used anywhere that text layout is
    needed, though most of the work on Pango so far has been done in the
    context of the GTK+ widget toolkit. Pango forms the core of text and font
    handling for GTK+-2.x.
  doc_url: http://www.pango.org/
  dev_url: https://github.com/phuang/pango

extra:
  recipe-maintainers:
    - ocefpaf
    - ccordoba12
    - jakirkham
    - pkgw
