{% set major = "1.40" %}
{% set patch = "4" %}
{% set version = major + "." + patch %}

package:
  name: pango
  version: {{ version }}

source:
  url: http://ftp.gnome.org/pub/GNOME/sources/pango/{{ major }}/pango-{{ version }}.tar.xz
  fn: pango-{{ version }}.tar.xz
  sha256: f8fdc5fc66356dc4edf915048cceeee065a0e0cb70b3b2598f62bda320129a3e

build:
  number: 0
  skip: true  # [win or py3k]
  detect_binary_files_with_prefix: true

requirements:
  build:
    - {{ compiler('c') }}
    - python >=2.7,<3  # [not win]
  host:
    - libpng
    - perl 5.*
    - pkg-config
    - harfbuzz 1.4.*
    # NOTE: harfbuzz installs everything that pango needs, but to avoid issues
    # with defaults we need to pin against conda-forge versions.
    - fontconfig 2.12.*
    - freetype 2.7|2.7.*
    - gobject-introspection  # [not win]
  run:
    - harfbuzz 1.4.*
    - fontconfig 2.12.*
    - freetype 2.7|2.7.*

test:
  commands:
    - pango-view --help
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: http://www.pango.org/
  license: LGPL-2.1
  license_file: COPYING
  summary: 'Text layout and rendering engine.'
  description: |
    Pango is a library for laying out and rendering of text, with an emphasis
    on internationalization. Pango can be used anywhere that text layout is
    needed, though most of the work on Pango so far has been done in the
    context of the GTK+ widget toolkit. Pango forms the core of text and font
    handling for GTK+-2.x.
  doc_url: http://www.pango.org/
  dev_url: https://github.com/phuang/pango

extra:
  recipe-maintainers:
    - ocefpaf
    - ccordoba12
    - jakirkham
    - pkgw
