{% set major = "1.40" %}
{% set patch = "3" %}
{% set version = major + "." + patch %}

package:
  name: pango
  version: {{ version }}

source:
  url: http://ftp.gnome.org/pub/GNOME/sources/pango/{{ major }}/pango-{{ version }}.tar.xz
  fn: pango-{{ version }}.tar.xz
  sha256: abba8b5ce728520c3a0f1535eab19eac3c14aeef7faa5aded90017ceac2711d3

build:
  number: 0
  skip: True  # [win]
  detect_binary_files_with_prefix: true

requirements:
  build:
    - perl
    - pkg-config
    - harfbuzz 1.3.*
    # FIXME: harfbuzz install everything that pango needs, but to avoid issues
    # with defaults we need to pin against conda-forge versions.
    - fontconfig 2.11.*
    - freetype 2.6.*
    - libpng >=1.6.23,<1.7
  run:
    - harfbuzz 1.3.*
    - fontconfig 2.11.*
    - freetype 2.6.*
    - libpng >=1.6.23,<1.7
test:
  commands:
    - pango-view --help
    - conda inspect linkages -p $PREFIX pango  # [not win]
    - conda inspect objects -p $PREFIX pango  # [osx]

about:
  home: http://www.pango.org/
  license: LGPL-2.1
  license_file: COPYING
  summary: 'Text layout and rendering engine.'
  description: |
    Pango is a library for laying out and rendering of text, with an emphasis
    on internationalization. Pango can be used anywhere that text layout is
    needed, though most of the work on Pango so far has been done in the
    context of the GTK+ widget toolkit. Pango forms the core of text and font
    handling for GTK+-2.x.
  doc_url: http://www.pango.org/
  dev_url: https://github.com/phuang/pango

extra:
  recipe-maintainers:
    - ocefpaf
    - ccordoba12
    - jakirkham
