{% set major = "1.48" %}
{% set patch = "7" %}
{% set version = major + "." + patch %}

package:
  name: pango
  version: {{ version }}

source:
  url: http://ftp.gnome.org/pub/GNOME/sources/pango/{{ major }}/pango-{{ version }}.tar.xz
  sha256: 28a82f6a6cab60aa3b75a90f04197ead2d311fa8fe8b7bfdf8666e2781d506dc

build:
  number: 0
  skip: true  # [win]
  detect_binary_files_with_prefix: true
  run_exports:
    # excellent: https://abi-laboratory.pro/tracker/timeline/pango/
    - {{ pin_subpackage('pango') }}
  ignore_run_exports:
    - libcxx          # [osx]
    - libstdcxx-ng    # [linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}   # `meson setup` requires this for built-in tests
    - {{ cdt('libxau-devel') }}           # [linux]
    - {{ cdt('libxext-devel') }}          # [linux]
    - {{ cdt('libx11-devel') }}           # [linux]
    - {{ cdt('libxcb') }}                 # [linux]
    - {{ cdt('libxrender-devel') }}       # [linux]
    - {{ cdt('xorg-x11-proto-devel') }}   # [linux and s390x]
    - make                                # [unix]
    - meson
    - ninja
    - pkg-config
    - gobject-introspection              # [not win]
  host:
    - cairo
    - fontconfig
    - freetype
    - fribidi
    - glib
    - harfbuzz >=2.0.0
    - pkg-config
    - libpng
    - gobject-introspection              # [not win]
test:
  commands:
    - pango-list --help
    - pango-view --help
    # Ensure gobject introspection data got built; refer to `build.sh` for why
    # this is currently disabled for macOS.
    - test -f $PREFIX/share/gir-1.0/Pango-1.0.gir   # [linux]

about:
  home: http://www.pango.org/
  license: LGPL-2.1
  license_file: COPYING
  summary: 'Text layout and rendering engine.'
  description: |
    Pango is a library for laying out and rendering of text, with an emphasis
    on internationalization. Pango can be used anywhere that text layout is
    needed, though most of the work on Pango so far has been done in the
    context of the GTK+ widget toolkit. Pango forms the core of text and font
    handling for GTK+-2.x.
  doc_url: http://www.pango.org/
  dev_url: https://github.com/phuang/pango

extra:
  recipe-maintainers:
    - ocefpaf
    - ccordoba12
    - jakirkham
    - pkgw
    - chenghlee
