travis:
  secure:
    BINSTAR_TOKEN: SOXlOnOjZlCdyitbhZ5OLQfsbIEyYDE8l9noEUkcqtimJF/qK5Fts8t2p7WxzsBE22sdlTjZ96E/3n2RSRYT5F8kfK7LEvfaVCIuCmWudV4Od5yJTO+L7mL75/dXF3DNjhHeyTNgDGmro6HFHcZxLBSGlnl3i9z4EIzHSGyP22CuHp6rsVSX95A72Pa+Hh9vPST8/h/YzGlXEXvdPX+RL1vz1UoaC/0tIOJ/GBM0Jhy1f5QzMUZdNKxn94VJhq+sCHBZQ3AAmgENAI9qcjEln4Fo6qe5uLQ44yhoFi/qV2HFV6OwmGudZB/c71pa2NrcAV1QkOIH2o+yUNZRVXs2aughroPOv1uR9Re5hrcBtWn8yfD3vnAKWlBn1oiB1iwzGWZ5eqFqJsGvd+I4Q0YUiIAjsw40WHpeU/wtFRTTgnbQL9QWiQ2FWrGbjQpI6jsWqF8DWQnUcuESTYAoMDsM1pUK2RvZyXp6jS/1FFQapi5B0Zzt4kbVFQBwMPBoTdWlCT4kT5zk1ps06aXAX3wgikyu4unHotPeZRmYW0VETO8IN8EA81oIZP28qIqL/6Cs5T71y4Z6RJ4nBufMN7KVAAk6tSkjKlmfOKLSxa7NCEi03mbmzuXXOufVgLonToV831ltpVQ7t7kLbB+UMEXFbAgOza4rCzhplWeEKc/9svk=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
