travis:
  secure:
    BINSTAR_TOKEN: moCpCtgIO+0IU491vPXyLNyuoejRVq+AlPNgEZ2j4daxWapQMjgB52w9s3LG83NZr0P87ETihGjoAgwJnKMTj0VwAvSldB71OS2/LYg+K3QDMtCTtUd5jB6XWYMx2GkyLpA5RbaeGpC+hZP/1OfsZhxPxthrCYIJdjy2ZhS/h0729mRwxOlFLAXKGip8cIvFBaGXA6Nc+Tfuj+Ckf+/gunzeCHXWTaXgh0nsD8ptgL9XYt3n4sUlGIIJgkTnxPOhmJXOoe0DtC3i/ZCfHnZfpiH8NjdDU7lYw5q361CDCVgD8iI73QIX7fOCbUi7WWJ0keCseomIdhdflKfXHuOSfRWbNJ3LUjysUIUuQlQjQZDc5QjHOhrckSUUhA6VFb0tJa7XhEIglDmZqUExG8ROAbe+hmmxpuG0oHhpKKvUCO3K81t12Tnw4b9ddhChcHEiMyBIn8Hn4O9iAib2M12dHfSRYqtrVi6xeyxMSPQRHLbBE/wSRAN9oNU10tQvk2Wi/74JCUuP+hdr1ntTeX0Cat7Om6+FedQNCG0k+fjf5QwwPrP6B34unPlRYxOL9gTPo9Jljzc+XGRuD3Nz3yLD0YViLqidDunk/C514+7EjLF8yDyzpPcZeNI7Pq1ARdvRwTazZGogw5fQg747fiJWBUi+hBZdTkmz+KsphlRmyYc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
